#!/usr/bin/env python3

import cs50
import sys
from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        print("Usage python tweets @username")
    s = sys.argv[1]
    s = s.strip('@')
    
    tweetlist = get_user_timeline(s, 100)
    analyzer = Analyzer("positive-words.txt", "negative-words.txt")
    
    for i in range(len(tweetlist)):
        score = analyzer.analyze(tweetlist[i])
        if score > 0.0:
            print(colored(score, "green"), end="")
            print(" ", end="")
            print(colored(tweetlist[i], "green"))
        elif score < 0.0:
            print(colored(score, "red"), end="")
            print(" ", end="")
            print(colored(tweetlist[i], "red"))
        else:
            print(colored(0, "yellow"), end="")
            print(" ", end="")
            print(colored(tweetlist[i], "yellow"))
    


main()